In [1]:
print("Hello Numpy")

Hello Numpy


In [2]:
import numpy as np
import time
import sys

In [98]:
l=range(10000)
print(sys.getsizeof(5)*len(l))

280000


In [42]:
array = np.arange(10000)
print(array.size*array.itemsize)

40000


# Get Started With Array...

In [7]:
a=np.array([3,1,2])

In [8]:
a.ndim

1

In [9]:
a

array([3, 1, 2])

In [10]:
b=np.array([[1,2,3],[4,5,6]])

In [11]:
b.ndim

2

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a

array([3, 1, 2])

In [14]:
a.itemsize

4

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.itemsize

4

In [17]:
b.dtype

dtype('int32')

In [18]:
a.dtype

dtype('int32')

# change the data type of an array

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b=np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [23]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
b.dtype

dtype('float64')

In [25]:
b.itemsize

8

In [26]:
b.size

6

In [27]:
b.shape

(2, 3)

In [28]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
b=np.array([[1,2,3],[4,5,6]], dtype=np.complex)

In [30]:
b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [31]:
r=np.array([[1,3,2],[4,3,2]])

In [32]:
r

array([[1, 3, 2],
       [4, 3, 2]])

In [33]:
r=np.array([[1,3,2],[4,3,2]], dtype=complex)

In [35]:


r

array([[1.+0.j, 3.+0.j, 2.+0.j],
       [4.+0.j, 3.+0.j, 2.+0.j]])

# Creating Numpy Array Using Just Dimensions

In [36]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Functions in Numpy

In [38]:
l=range(10)

In [39]:
l

range(0, 10)

In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,10,3)

array([1, 4, 7])

In [46]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [47]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [52]:
t=np.array([[1,2,3],[3,4,5],[3,4,5],[1,3,2]])

In [53]:
t.shape

(4, 3)

In [54]:
t.reshape(3,4)

array([[1, 2, 3, 3],
       [4, 5, 3, 4],
       [5, 1, 3, 2]])

In [59]:
t.ravel()

array([1, 2, 3, 3, 4, 5, 3, 4, 5, 1, 3, 2])

In [60]:
t

array([[1, 2, 3],
       [3, 4, 5],
       [3, 4, 5],
       [1, 3, 2]])

# Mathematical Functions In Numpy

In [61]:
x=np.array([[1,2,3],[3,5,4]])
y=np.array([[1,2,3],[1,2,3]])
x.min()

1

In [62]:
y.min()

1

In [63]:
x.max()

5

In [64]:
y.max()

3

In [67]:
x.sum(axis=0)

array([4, 7, 7])

In [68]:
y.sum(axis=1)

array([6, 6])

In [70]:
# y.sum(x)

In [72]:
x

array([[1, 2, 3],
       [3, 5, 4]])

In [76]:
# y.sqrt()


In [77]:
A=np.array([[1,2,3],[3,4,5]])

In [78]:
A

array([[1, 2, 3],
       [3, 4, 5]])

In [82]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [83]:
x

array([[1, 2, 3],
       [3, 5, 4]])

In [84]:
y

array([[1, 2, 3],
       [1, 2, 3]])

In [85]:
x+y

array([[2, 4, 6],
       [4, 7, 7]])

In [86]:
x-y

array([[0, 0, 0],
       [2, 3, 1]])

In [87]:
x*y

array([[ 1,  4,  9],
       [ 3, 10, 12]])

In [88]:
x/y

array([[1.        , 1.        , 1.        ],
       [3.        , 2.5       , 1.33333333]])

In [89]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.23606798, 2.        ]])

In [90]:
np.sqrt(y)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [93]:
# x.dot(y)

In [94]:
A=np.array([[1,2],[2,3]])
B=np.array([[2,3],[4,5]])

In [95]:
A.dot(B)

array([[10, 13],
       [16, 21]])

# Numpy Array Slicing

In [99]:
d=np.array([1,2,3,4,5,6,7])

In [100]:
d[0:3]

array([1, 2, 3])

In [101]:
d[-1]

7

In [102]:
e=np.array([[1,2,3],[2,3,4],[1,2,3]])

In [103]:
e

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3]])

In [105]:
e[1,2]

4

In [107]:
e[0:3, 2]

array([3, 4, 3])

In [108]:
e[0:3,0]

array([1, 2, 1])

In [109]:
e

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3]])

In [110]:
e[-1]

array([1, 2, 3])

In [111]:
e[-2]

array([2, 3, 4])

In [112]:
e[-1,0:2]

array([1, 2])

In [116]:
e[:,1:3]

array([[2, 3],
       [3, 4],
       [2, 3]])

In [117]:
for row in e:
    print(e)

[[1 2 3]
 [2 3 4]
 [1 2 3]]
[[1 2 3]
 [2 3 4]
 [1 2 3]]
[[1 2 3]
 [2 3 4]
 [1 2 3]]


In [119]:
for cell in e.flat:
    print(cell)

1
2
3
2
3
4
1
2
3


# Stacking Numpy Arrays

In [126]:
f=np.arange(6).reshape(3,2)
g=np.arange(6,12).reshape(3,2)

In [123]:
f

array([[0, 1],
       [2, 3],
       [4, 5]])

In [127]:
g

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [131]:
np.vstack((f,g))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [132]:
np.hstack((f,g))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [143]:
h=np.arange(30).reshape(2,15)

In [144]:
np.hsplit(h, 3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [145]:
np.hsplit(h,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [153]:
re=np.hsplit(h,3)

In [154]:
re[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [155]:
re[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [157]:
re=np.hsplit(h,3)

In [158]:
re

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [159]:
re[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [178]:
re=np.vsplit(h,2)

In [175]:
# resu=np.vsplit(f,2)

In [179]:
re

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [180]:
re[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [181]:
re[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Iterate Using nditer In Numpy 

In [182]:
j=np.arange(12).reshape(3,4)

In [183]:
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
for row in j:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [194]:
for cell in j.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [198]:
for k in np.nditer(j, order="C"):
    print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [200]:
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
for k in np.nditer(j, order="F"):
    print(k)

0
4
8
1
5
9
2
6
10
3
7
11


In [203]:
for k in np.nditer(j, order='F', flags=['external_loop']):
    print(k)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [207]:
for o in np.nditer(j, order="F", op_flags=['readwrite'] ):
    o[...]=o*o

In [208]:
j

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])